### PR TITLE
Enable carthage

### PR DESCRIPTION
**Pull request by JonasVautherin**
Update the SDK repo to work with Carthage.

I tried to create a `Cartfile` with the following content somewhere (say, `/tmp/test/Cartfile`):

    github "Dronecode/DronecodeSDK-Swift" "enable-carthage"

And it built all the frameworks when I ran `$ carthage update --platform ios`. Seems to me that it is exactly what we want.

Also note that the example app is now in https://github.com/Dronecode/DronecodeSDK-Swift-Example.

### CODE REVIEW

**Comment by julianoes** [comment]
Can we still use the scripts to build manually for debugging like I did int #64?

**Comment by JonasVautherin** [comment]
We can still build the frameworks manually, but the project looks for them in `Carthage/Build/iOS/`. So either that need to be changed in the project config (which is probably not ideal), or the manually-built frameworks can be copied into `Carthage/Build/iOS`. 

However, it could be that it is easier to just use Carthage: say you develop in MFiExample in parallel to DronecodeSDK: you can work in a feature branch in DronecodeSDK, and make MFiExample depend on it through Carthage. Does that make sense?

**Comment by julianoes** [comment]
> make MFiExample depend on it through Carthage. Does that make sense?

but that will do a full rebuild each time, right?

**Comment by JonasVautherin** [comment]
> But that will do a full rebuild each time, right?

Oh, because you need to remove `Cartfile.resolved` if you want it to rebuild the SDK? What if you only remove the SDK line in `Cartfile.resolved`? In my (limited) experience, when I added a dependency, it did not rebuild the others.

**Comment by julianoes** [comment]
Ok, I can try it.

**Pull request merged**
