### PR TITLE
Point to the working commit of gRPC-Swift to fix Cartgage builds

### LINKED ISSUE #120: Error building SDK from Carthage
Keep get this error when trying to run `carthage bootstrap --platform ios`:

```
3DR-000328:Downloads douglas$ cd /Users/douglas/Downloads/DronecodeSDK-Swift-master\ 2 
3DR-000328:DronecodeSDK-Swift-master 2 douglas$ carthage bootstrap --platform ios
*** Checking out grpc-swift at "0.8.1"
*** Checking out RxSwift at "4.5.0"
*** Downloading binary-only framework backend at "https://s3.eu-central-1.amazonaws.com/dronecode-sdk/backend.json"
*** xcodebuild output can be found in /var/folders/2d/t05mnyvs1ll3z81lgn1xlqgw0000gp/T/carthage-xcodebuild.nGAape.log
*** Downloading RxSwift.framework binary at "[4,5]"
***  Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source
*** Building scheme "SwiftGRPC-Package" in SwiftGRPC-Carthage.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/douglas/Downloads/DronecodeSDK-Swift-master\ 2/Carthage/Checkouts/grpc-swift/SwiftGRPC-Carthage.xcodeproj -scheme SwiftGRPC-Package -configuration Release -derivedDataPath /Users/douglas/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/grpc-swift/0.8.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2d/t05mnyvs1ll3z81lgn1xlqgw0000gp/T/grpc-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/douglas/Downloads/DronecodeSDK-Swift-master 2/Carthage/Checkouts/grpc-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2d/t05mnyvs1ll3z81lgn1xlqgw0000gp/T/carthage-xcodebuild.nGAape.log
3DR-000328:DronecodeSDK-Swift-master 2 douglas$ 
```

NOTE: We're using XCode 10.1

### PR DESCRIPTION
**Pull request by byuarus**
Resolves #120

### CODE REVIEW

**Comment by byuarus** [comment]
@JonasVautherin I've tried `0.8.2` and `0.8.1`.
The `0.8.2` fails but `0.8.1` works, so it's ok if you will point strictly to `0.8.1` until swift-grpc will release the version that will work.

**Comment by JonasVautherin** [comment]
Ok, let me do that fix in another PR.

I note that `~>` is a mistake for the SDK, as it creates issues like this. We should always use `==` and update everything manually.

Sorry for this issue then, let me push a fix now!

**Comment by julianoes** [comment]
> I note that ~> is a mistake for the SDK, as it creates issues like this. We should always use == and update everything manually.

Why? Shouldn't you just do `carthage bootstrap` and not `carthage update`?

**Comment by JonasVautherin** [comment]
`carthage update` should not break your build anyway. Turns out that grpc-swift `0.8.2` is breaking ours, so we don't want our configuration to automatically move to broken versions :sweat_smile:.

**Pull request closed without merging**
